name: PlayerList
version: 1.0.0
author: Etrenak
main: fr.etrenak.playerlist.PlayerList

commands:
  PlayerList:
   aliases: [ListJoueur, pList]
   permission: PlayerList.PlayerList

permissions:
  PlayerList.PlayerList:
    default: op
